# Generated by Django 5.1 on 2024-09-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortlistedProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255)),
                ('number', models.CharField(blank=True, max_length=15, null=True)),
                ('properties', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
