# Generated by Django 5.1 on 2024-11-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SorterSession', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlistedproperty',
            name='selectedproperties',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
