# Generated by Django 5.1 on 2024-11-20 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SorterSession', '0002_shortlistedproperty_selectedproperties'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortlistedproperty',
            old_name='selectedproperties',
            new_name='selected_properties',
        ),
    ]
