# Generated by Django 5.1 on 2024-11-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SorterSession', '0003_rename_selectedproperties_shortlistedproperty_selected_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlistedproperty',
            name='visit_details',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
