# Generated by Django 5.1 on 2024-11-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SorterSession', '0004_shortlistedproperty_visit_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlistedproperty',
            name='start_visit_time_date',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
