# Generated by Django 5.1 on 2024-11-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SorterSession', '0005_shortlistedproperty_start_visit_time_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlistedproperty',
            name='visit_start_coords',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shortlistedproperty',
            name='visit_start_location',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
