# Generated by Django 5.1 on 2024-11-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SorterSession', '0006_shortlistedproperty_visit_start_coords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlistedproperty',
            name='feedback',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
