# Generated by Django 5.1 on 2024-11-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SorterSession', '0007_shortlistedproperty_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlistedproperty',
            name='visist_finalize',
            field=models.BooleanField(default=False),
        ),
    ]
