# Generated by Django 5.1 on 2024-11-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SorterSession', '0008_shortlistedproperty_visist_finalize'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlistedproperty',
            name='visit_plan_pdf',
            field=models.FileField(blank=True, null=True, upload_to='visit_plan'),
        ),
    ]
