# Generated by Django 5.1 on 2024-11-29 14:47

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SorterSession', '0009_shortlistedproperty_visit_plan_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlistedproperty',
            name='visit_plan_pdf',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='visit_plan'),
        ),
    ]
