# Generated by Django 5.1 on 2024-12-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SorterSession', '0010_alter_shortlistedproperty_visit_plan_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlistedproperty',
            name='feedback',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
