# Generated by Django 5.1 on 2024-12-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SorterSession', '0013_alter_shortlistedproperty_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlistedproperty',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
