# Generated by Django 5.1 on 2025-05-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SorterSession', '0014_shortlistedproperty_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlistedproperty',
            name='hidden_properties',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
