# Generated by Django 5.1 on 2025-05-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SorterSession', '0015_shortlistedproperty_hidden_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlistedproperty',
            name='distance_order_selected_properties',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
