# Generated by Django 5.1 on 2025-05-29 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SorterSession', '0016_shortlistedproperty_distance_order_selected_properties'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortlistedproperty',
            old_name='distance_order_selected_properties',
            new_name='distance_order_properties',
        ),
    ]
