# Generated by Django 5.1 on 2025-06-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SorterSession', '0017_rename_distance_order_selected_properties_shortlistedproperty_distance_order_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlistedproperty',
            name='base_price_order_properties',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
