# Generated by Django 5.1 on 2024-09-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingdetails',
            name='head_image',
            field=models.ImageField(default=None, upload_to='property'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildingdetails',
            name='sec_image_1',
            field=models.ImageField(default=None, upload_to='property'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildingdetails',
            name='sec_image_2',
            field=models.ImageField(default=None, upload_to='property'),
            preserve_default=False,
        ),
    ]
