# Generated by Django 5.1 on 2024-09-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0002_buildingdetails_head_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitdetails',
            name='building_id',
            field=models.CharField(max_length=255),
        ),
    ]
