# Generated by Django 5.1 on 2024-09-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0003_alter_unitdetails_building_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitdetails',
            name='google_pin',
            field=models.CharField(default='', max_length=255),
        ),
    ]
