# Generated by Django 5.1 on 2024-09-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0006_unitdetails_location_of_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitdetails',
            name='location_of_project',
        ),
        migrations.AddField(
            model_name='unitdetails',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
