# Generated by Django 5.1 on 2024-09-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0007_remove_unitdetails_location_of_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingdetails',
            name='spiritual_or_religious_attraction',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
