# Generated by Django 5.1 on 2024-09-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0009_buildingdetails_rera_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingdetails',
            name='rera_approved',
            field=models.BooleanField(default=False),
        ),
    ]
