# Generated by Django 5.1 on 2024-10-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0010_alter_buildingdetails_rera_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingdetails',
            name='alternate_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='buildingdetails',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
    ]
