# Generated by Django 5.1 on 2024-10-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0011_buildingdetails_alternate_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingdetails',
            name='plc',
        ),
        migrations.AddField(
            model_name='buildingdetails',
            name='plc_corner',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='buildingdetails',
            name='plc_garden',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='buildingdetails',
            name='plc_others',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='buildingdetails',
            name='plc_road_facing',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='buildingdetails',
            name='sale_deed_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='floor_rise',
            field=models.TextField(blank=True, null=True),
        ),
    ]
