# Generated by Django 5.1 on 2024-10-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0012_remove_buildingdetails_plc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildingdetails',
            old_name='age_of_property_developer',
            new_name='age_of_property_by_developer',
        ),
        migrations.AddField(
            model_name='unitdetails',
            name='size_of_balcony',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='unitdetails',
            name='size_of_kitchen',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='unitdetails',
            name='size_of_master_bedroom',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
