# Generated by Django 5.1 on 2024-10-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0014_alter_buildingdetails_advance_maintenance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingdetails',
            name='age_of_property_by_developer',
            field=models.TextField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='age_of_property_rera',
            field=models.TextField(blank=True, default='', max_length=15, null=True),
        ),
    ]
