# Generated by Django 5.1 on 2024-10-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0016_alter_buildingdetails_developed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingdetails',
            name='advance_maintenance',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='development_charges',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='gst_applicable',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='maintenance_deposit',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='other_specific_expenses',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='plc_corner',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='plc_garden',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='plc_others',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='plc_road_facing',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='sale_deed_value',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='sale_deed_value_max',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='sale_deed_value_min',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
    ]
