# Generated by Django 5.1 on 2024-10-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0017_alter_buildingdetails_advance_maintenance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingdetails',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unitdetails',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='unitdetails',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
