# Generated by Django 5.1 on 2024-10-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0018_buildingdetails_active_unitdetails_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingdetails',
            name='possession_by',
            field=models.TextField(blank=True, default='', max_length=15, null=True),
        ),
    ]
