# Generated by Django 5.1 on 2024-10-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0019_buildingdetails_possession_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingdetails',
            name='brochure_1',
            field=models.FileField(blank=True, null=True, upload_to='brochure'),
        ),
        migrations.AddField(
            model_name='buildingdetails',
            name='brochure_2',
            field=models.FileField(blank=True, null=True, upload_to='brochure'),
        ),
        migrations.AddField(
            model_name='buildingdetails',
            name='sec_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='property'),
        ),
        migrations.AddField(
            model_name='buildingdetails',
            name='sec_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='property'),
        ),
    ]
