# Generated by Django 5.1 on 2024-10-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0021_buildingdetails_special_amenity'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingdetails',
            name='per_sqft_rate_saleable',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='unitdetails',
            name='base_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unitdetails',
            name='carpet_area_rera',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='unitdetails',
            name='per_sqft_rate_saleable',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='unitdetails',
            name='size_of_balcony',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unitdetails',
            name='size_of_kitchen',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unitdetails',
            name='size_of_master_bedroom',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unitdetails',
            name='size_of_private_terrace',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unitdetails',
            name='size_of_unit',
            field=models.CharField(max_length=100),
        ),
    ]
