# Generated by Django 5.1 on 2024-10-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0022_buildingdetails_per_sqft_rate_saleable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitdetails',
            name='floor_plan',
            field=models.ImageField(blank=True, null=True, upload_to='plan'),
        ),
        migrations.AddField(
            model_name='unitdetails',
            name='unit_plan',
            field=models.ImageField(blank=True, null=True, upload_to='plan'),
        ),
    ]
