# Generated by Django 5.1 on 2024-10-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0023_unitdetails_floor_plan_unitdetails_unit_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingdetails',
            name='key_projects',
        ),
        migrations.RemoveField(
            model_name='buildingdetails',
            name='key_promoters',
        ),
        migrations.AddField(
            model_name='buildingdetails',
            name='key_projects_1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='buildingdetails',
            name='key_projects_2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='buildingdetails',
            name='key_projects_3',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='buildingdetails',
            name='key_projects_4',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='buildingdetails',
            name='key_projects_5',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='buildingdetails',
            name='key_promoters_1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='buildingdetails',
            name='key_promoters_2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='buildingdetails',
            name='key_promoters_3',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='buildingdetails',
            name='key_promoters_4',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='buildingdetails',
            name='key_promoters_5',
            field=models.CharField(default='', max_length=255),
        ),
    ]
