# Generated by Django 5.1 on 2024-10-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0024_remove_buildingdetails_key_projects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingdetails',
            name='special_amenity',
        ),
        migrations.AddField(
            model_name='buildingdetails',
            name='special_amenity_1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='buildingdetails',
            name='special_amenity_2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='buildingdetails',
            name='special_amenity_3',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='buildingdetails',
            name='special_amenity_4',
            field=models.CharField(default='', max_length=255),
        ),
    ]
