# Generated by Django 5.1 on 2024-10-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0025_remove_buildingdetails_special_amenity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingdetails',
            name='key_projects_1',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='key_projects_2',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='key_projects_3',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='key_projects_4',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='key_projects_5',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='key_promoters_1',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='key_promoters_2',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='key_promoters_3',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='key_promoters_4',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='key_promoters_5',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='special_amenity_1',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='special_amenity_2',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='special_amenity_3',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='special_amenity_4',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
