# Generated by Django 5.1 on 2024-10-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0028_rename_cctv_surveillance_amenities_activity_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingdetails',
            name='alternate_number_country_code',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='buildingdetails',
            name='number_country_code',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
