# Generated by Django 5.1 on 2024-10-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0030_rename_size_of_balcony_unitdetails_size_of_balcony_len_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitdetails',
            name='no_private_lifts',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='no_of_basements',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='no_of_blocks',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='no_of_floors',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='no_of_units',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='unitdetails',
            name='no_of_attached_bathrooms',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='unitdetails',
            name='no_of_balconies',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='unitdetails',
            name='no_of_lifts_per_floor',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='unitdetails',
            name='no_of_parking_allotted',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='unitdetails',
            name='no_of_units_per_floor',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
