# Generated by Django 5.1 on 2024-10-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0031_unitdetails_no_private_lifts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitdetails',
            name='unit_series',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
