# Generated by Django 5.1 on 2024-10-21 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0032_unitdetails_unit_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingdetails',
            name='developed_by',
        ),
        migrations.RemoveField(
            model_name='buildingdetails',
            name='pet_friendly',
        ),
    ]
