# Generated by Django 5.1 on 2024-10-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0034_alter_buildingdetails_architect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingdetails',
            name='no_of_projects_delivered',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='year_of_establishment',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='unitdetails',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
