# Generated by Django 5.1 on 2024-11-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0035_alter_buildingdetails_no_of_projects_delivered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingdetails',
            name='no_of_basements',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='no_of_blocks',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='no_of_floors',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='no_of_units',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='unitdetails',
            name='no_of_attached_bathrooms',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='unitdetails',
            name='no_of_balconies',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='unitdetails',
            name='no_of_lifts_per_floor',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='unitdetails',
            name='no_of_parking_allotted',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='unitdetails',
            name='no_of_units_per_floor',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='unitdetails',
            name='no_private_lifts',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
