# Generated by Django 5.1 on 2024-11-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0036_alter_buildingdetails_no_of_basements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingdetails',
            name='central_air_conditioning',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
