# Generated by Django 5.1 on 2024-11-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0037_alter_buildingdetails_central_air_conditioning'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitdetails',
            name='carpet_size_terrace',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unitdetails',
            name='private_terrace',
            field=models.BooleanField(default=False),
        ),
    ]
