# Generated by Django 5.1 on 2024-11-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0038_unitdetails_carpet_size_terrace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitdetails',
            name='floor_to_ceiling',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
