# Generated by Django 5.1 on 2024-11-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0039_unitdetails_floor_to_ceiling'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingdetails',
            name='rera_by_when',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
