# Generated by Django 5.1 on 2024-11-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0041_unitdetails_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitdetails',
            name='group_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
