# Generated by Django 5.1 on 2024-11-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0042_unitdetails_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingdetails',
            name='head_image',
            field=models.ImageField(blank=True, null=True, upload_to='property/'),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='sec_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='property/'),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='sec_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='property/'),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='sec_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='property/'),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='sec_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='property/'),
        ),
    ]
