# Generated by Django 5.1 on 2024-11-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0043_alter_buildingdetails_head_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingdetails',
            name='head_image',
            field=models.ImageField(blank=True, null=True, upload_to='https://ssc-disrupt.s3.amazonaws.com/property/'),
        ),
    ]
