# Generated by Django 5.1 on 2024-11-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0044_alter_buildingdetails_head_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingdetails',
            name='head_image',
            field=models.ImageField(blank=True, null=True, upload_to='property/'),
        ),
    ]
