# Generated by Django 5.1 on 2024-11-29 14:38

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0045_alter_buildingdetails_head_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingdetails',
            name='head_image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='property/'),
        ),
    ]
