# Generated by Django 5.1 on 2024-11-29 14:47

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0046_alter_buildingdetails_head_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingdetails',
            name='brochure_1',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='brochure'),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='brochure_2',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='brochure'),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='sec_image_1',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='property/'),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='sec_image_2',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='property/'),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='sec_image_3',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='property/'),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='sec_image_4',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='property/'),
        ),
        migrations.AlterField(
            model_name='unitdetails',
            name='floor_plan',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='plan'),
        ),
        migrations.AlterField(
            model_name='unitdetails',
            name='unit_plan',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='plan'),
        ),
    ]
