# Generated by Django 5.1 on 2024-12-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0047_alter_buildingdetails_brochure_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingdetails',
            name='property_added_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
