# Generated by Django 5.1 on 2024-12-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0048_buildingdetails_property_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingdetails',
            name='brokerage',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
