# Generated by Django 5.1 on 2025-01-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0049_buildingdetails_brokerage'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingdetails',
            name='spiritual_or_religious_attraction_text',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='buildingdetails',
            name='spiritual_or_religious_attraction',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
