# Generated by Django 5.1 on 2025-01-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0050_buildingdetails_spiritual_or_religious_attraction_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingdetails',
            name='sample_house',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buildingdetails',
            name='sample_house_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
