# Generated by Django 5.1 on 2025-01-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0051_buildingdetails_sample_house_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitdetails',
            name='uploaded_extra_plans',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
