# Generated by Django 5.1 on 2025-02-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0052_unitdetails_uploaded_extra_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitdetails',
            name='no_of_floors',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
