# Generated by Django 5.1 on 2025-02-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0053_unitdetails_no_of_floors'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitdetails',
            name='central_air_conditioning',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unitdetails',
            name='type_of_parking',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
