# Generated by Django 5.1 on 2025-03-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0054_unitdetails_central_air_conditioning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingdetails',
            name='per_sqft_rate_saleable_duplex',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buildingdetails',
            name='per_sqft_rate_saleable_penthouse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unitdetails',
            name='per_sqft_rate_saleable_duplex',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unitdetails',
            name='per_sqft_rate_saleable_penthouse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
