# Generated by Django 5.1 on 2025-03-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0055_buildingdetails_per_sqft_rate_saleable_duplex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingdetails',
            name='jodi_possible',
            field=models.BooleanField(default=False),
        ),
    ]
