# Generated by Django 5.1 on 2025-03-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0056_buildingdetails_jodi_possible'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitdetails',
            name='count_of_hydraulic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unitdetails',
            name='count_of_normal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
