# Generated by Django 5.1 on 2025-03-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0057_unitdetails_count_of_hydraulic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingdetails',
            name='down_payment_as_on_date',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
