# Generated by Django 5.1 on 2025-03-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0058_buildingdetails_down_payment_as_on_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingdetails',
            name='property_created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-03-24 10:00'),
            preserve_default=False,
        ),
    ]
