# Generated by Django 5.1 on 2025-03-24 04:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0059_buildingdetails_property_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingdetails',
            name='property_created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 24, 4, 38, 54, 241125, tzinfo=datetime.timezone.utc)),
        ),
    ]
