# Generated by Django 5.1 on 2025-03-24 04:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0060_alter_buildingdetails_property_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingdetails',
            name='property_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
