# Generated by Django 5.1 on 2024-10-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientDetail', '0002_remove_propertyinquiry_vastu_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyinquiry',
            name='unit_type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
