# Generated by Django 5.1 on 2024-10-17 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientDetail', '0003_propertyinquiry_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyinquiry',
            name='country_code',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='whatsapp_country_code',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
