# Generated by Django 5.1 on 2024-10-21 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClientDetail', '0004_propertyinquiry_country_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyinquiry',
            name='have_pets',
        ),
    ]
