# Generated by Django 5.1 on 2024-10-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientDetail', '0005_remove_propertyinquiry_have_pets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyinquiry',
            name='unit_type',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
