# Generated by Django 5.1 on 2024-12-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientDetail', '0006_alter_propertyinquiry_unit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyinquiry',
            name='society_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
