# Generated by Django 5.1 on 2024-12-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientDetail', '0007_alter_propertyinquiry_society_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyinquiry',
            name='inquiry_added_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
