# Generated by Django 5.1 on 2025-05-25 19:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientDetail', '0008_propertyinquiry_inquiry_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyinquiry',
            name='inquiry_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
