# Generated by Django 5.1 on 2025-07-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bunglows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bunglowdetails',
            name='open_space_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
