# Generated by Django 5.1 on 2025-07-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bunglows', '0002_bunglowdetails_open_space_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bunglowdetails',
            old_name='architect',
            new_name='project_architect',
        ),
        migrations.AddField(
            model_name='bunglowdetails',
            name='construction_rate_per_sq_yd',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bunglowdetails',
            name='land_zone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bunglowdetails',
            name='landscape_architect',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bunglowdetails',
            name='plot_rate_per_sq_yd',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bunglowdetails',
            name='sbu_on_construction',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bunglowdetails',
            name='sbu_on_plot',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
