# Generated by Django 5.1 on 2025-07-25 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bunglows', '0003_rename_architect_bunglowdetails_project_architect_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bunglowdetails',
            old_name='construction_company',
            new_name='construction',
        ),
    ]
