# Generated by Django 5.1 on 2025-07-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bunglows', '0004_rename_construction_company_bunglowdetails_construction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bunglowunitdetails',
            old_name='common_terrace_accessible',
            new_name='solar_available_on_roof_top',
        ),
        migrations.AddField(
            model_name='bunglowunitdetails',
            name='phase',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bunglowunitdetails',
            name='size_of_unit_max',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bunglowunitdetails',
            name='size_of_unit_min',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bunglowunitdetails',
            name='type',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
