# Generated by Django 5.1 on 2025-07-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bunglows', '0005_rename_common_terrace_accessible_bunglowunitdetails_solar_available_on_roof_top_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bunglowunitdetails',
            name='basement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bunglowunitdetails',
            name='basement_levels',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
