# Generated by Django 5.1 on 2025-07-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bunglows', '0006_bunglowunitdetails_basement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bunglowunitdetails',
            name='construction_size_sq_yd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
