# Generated by Django 5.1 on 2025-07-28 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bunglows', '0007_bunglowunitdetails_construction_size_sq_yd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bunglowunitdetails',
            name='phase',
        ),
        migrations.RemoveField(
            model_name='bunglowunitdetails',
            name='type',
        ),
    ]
